# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Create your Documentation
description: Home for the Documentation Creation
baseurl: "/pages/tomaspipes/docs-creation/"
url: "https://github.com"


# Build settings
markdown: kramdown
remote_theme: https://github.com/just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Collections settings
collections_dir: "srcs"

collections:
  knowledge_base:
    output: true

just_the_docs:
  collections:
    knowledge_base:
      name: Knowledge Base
      nav_fold: true

color_scheme: wider
